services:
  mongodb:
    image: mongo:6.0
    ports:
      - "27009:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - rss-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4009:4009"
    env_file:
      - ./backend/.env.development
    depends_on:
      - mongodb
    networks:
      - rss-network
    volumes:
      - /media/machi/Data/Dev/machi-workspace/machi-projects/machi00_ops/machi09_rss-feed/debug-logs:/app/logs

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3009:80"
    networks:
      - rss-network
    depends_on:
      - backend

networks:
  rss-network:
    driver: bridge

volumes:
  mongodb_data:
